### ISSUE TITLE
How about  convert html into javascript

### ISSUE THREAD

**Issue by huang-xiao-jian** [gartz/html#1]
Hi:
   personally I think, maybe we can convert html into javascript to avoid unnecessary network request, especially when there are a lot tiny template to load. you can see https://github.com/bornkiller/html/blob/master/html.js

**Comment by gartz** [comment]
It's a good idea, can you make a PR?

**Comment by gartz** [comment]
Actually if you want to use some other syntax that is not HTML, you can use a module to preprocess it, like **jade** or other. However the main goal with this project is to make cheap to the processor to render the template, any other process added to it will slowdown the rendering time.
